# main
verbose_main: false
main_iter_rate: 40
height: 2
look_ahead: 1
close_enough: 0.2
average_speed: 2.0
average_speed_z: 0.5

# motion
verbose_motion: true
use_ground_truth: false
debug_motion: false # this will record variance for sonar, baro and magento, will also keep track of mse of ekf estimate and ground truth
qa: 16
qx: 16
qy: 16
qz: 16
enable_gps: true
r_gps_x: 25.
r_gps_y: 25.
r_gps_z: 25.
enable_magnet: true
r_mgn_a: 0.000623964
enable_baro: true
r_bar_z: 0.123828
enable_sonar: true
r_snr_z: 0.0000234438
motion_iter_rate: 20

# move
enable_move: true
verbose_move: false
pid_tuning_z: false  # this will send set a z setpoint of 2m and record rise time and overshoot
pid_tuning_xy: false  # this will send a x setpoint of 2m and record rise time and overshoot, it is assumed that x and y are the same
Kp_lin: 0.5 
Ki_lin: 0
Kd_lin: 0.1
Kp_z: 2
Ki_z: 0
Kd_z: 0.4
yaw_rate: 0.5
max_lin_vel: 2
max_z_vel: 0.5
move_iter_rate: 40

# run param used automatically and should not be written